language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    sources:
    packages:
      - libibverbs-dev
      - libibmad-dev
      - libibumad-dev
      - libibnetdisc-dev
      - libopensm-dev

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: ./build.sh

before_deploy: tar -cf ibperf-lib-${TRAVIS_TAG}.tar -C build/ ar/libIbPerfLib.a bin/IbPerfTest bin/IbDiagPerfTest

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  file: ibperf-lib-${TRAVIS_TAG}.tar
  skip_cleanup: true
  overwrite: true
  on:
    repo: hhu-bsinfo/ibperf-lib
    branch: master
    tags: true
